#!/bin/bash

module purge
module load gcc/13.4.0
module load openmpi/5.0.8
module load netcdf-c/4.9.3
module load netcdf-fortran/4.6.2
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$NETCDF_FORTRAN_ROOT/lib
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$NETCDF_C_ROOT/lib