#!/bin/bash

module purge
module load gcc/12.4.0
module load openmpi/5.0.6
module load netcdf-c/4.9.2
module load netcdf-fortran/4.6.1
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$NETCDF_FORTRAN_ROOT/lib
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$NETCDF_C_ROOT/lib